### ISSUE TITLE
Controller not getting loaded 

### ISSUE THREAD

**Issue by Digambar14** [ocombe/ocLazyLoad#164]
I have written one controlller js LoginController.js. I want include it only for login state. So i have written code in app.js like

```
var FrontEnd = angular.module("FrontEnd", ['ui.router', 'oc.lazyLoad']);

FrontEnd.config(['$ocLazyLoadProvider', function($ocLazyLoadProvider) {
      // We configure ocLazyLoad to use the lib script.js as the async loader
      $ocLazyLoadProvider.config({
          
      });
  }]);

FrontEnd.config(function($stateProvider, $urlRouterProvider) { 
    
   
    $stateProvider
        .state('login', {
            url: '/login',
            templateUrl:  BASE_URL + '/default/index/template/name/login',
            controller: 'LoginController',
            resolve: {
                deps: ['$ocLazyLoad', function($ocLazyLoad) {
                    return $ocLazyLoad.load({
                        name: 'FrontEnd',
                        insertBefore: '#ng_load_plugins_before',
                        files: [
                            'js/controllers/LoginController.js'
                        ] 
                    });
                }]
            }
        });
       
    $urlRouterProvider.otherwise('/login');
});
```

And my LoginController.js is:

```
FrontEnd.controller('LoginController', function() {
    console.log("In Login Controller");
    
});
```

For now I am trying only to see where it comes in controller or not. When I directly include my LoginController.js in layout, it works perfectly but when I try with loading using lazy loader it gives me blank screen. It does not show even any error in console. Please help me out, its urgent. Using version 0.5.1.

Thanks.

**Comment by ocombe** [comment]
Hi, if you want to see the errors, you should add success & error callbacks to the load function (I should write this in the docs):
```
return $ocLazyLoad.load({
  // you don't have to give the name of the module anymore, I removed it
  insertBefore: '#ng_load_plugins_before',
  files: [
    'js/controllers/LoginController.js'
  ] 
}).then(function success(args) {
  console.log('success');
  return args;
}, function error(err) {
  console.log(err);
return err;
});
```

Then the problem here is probably that in your loginController.js file you reference "FrontEnd" but the global variable is probably not available in your file.

Change it to:
```js
angular.module("FrontEnd").controller('LoginController', function() {
    console.log("In Login Controller");

});
```

**Comment by Digambar14** [comment]
Thanks for reply. But its still not working.:( I tried to console error with your code. But still not showing any errors.

**Comment by ocombe** [comment]
OK, does an element with the id #ng_load_plugins_before really exist in
your Dom? Do you see the controller file being loaded in the network from
tab?

Also, what versions of angular and ocLazyLoad do you use?

**Comment by Digambar14** [comment]
Yes, DOM includes element with id #ng_load_plugins_before. 

No, I checked, controller file is not being loaded.

Using angular's v3.1.15 and ocLazyLoads v0.5.1.

**Comment by Digambar14** [comment]
Can you look into it using team viewer. Because I am fed up with it since last two days and its very urgent.

**Comment by ocombe** [comment]
I'm making a plunkr to reproduce the bug

**Comment by ocombe** [comment]
Ok, if I remove "insertBefore: '#ng_load_plugins_before'" it works. You can use this for now (unless this parameter is really really necessary for you?), I need to check why "insertBefore" isn't working.

**Comment by Digambar14** [comment]
Yes boss. Thank you very much. "insertBefore" is not working. Its not that much necessary for me but wanted to keep my controllers file in above particular div. But let me know if you resolve the issue of insertBefore.

Once again thanks.:)

**Comment by ocombe** [comment]
I'm using `angular.element` to get the element, and for some reason it doesn't work. If I change it to document.querySelector then it works fine...
I'll need to debug further to know why.

**Comment by Digambar14** [comment]
But getting this error in console: SyntaxError: expected expression, got '<'.

If I manually load LoginController.js into layout it works fine. And I checked in dom its not getting included in DOM but in Network its showing js is being loaded.

**Comment by ocombe** [comment]
Here is a working version of your code (I might have changed a few file names/urls to make it work on plunkr): http://plnkr.co/edit/tqDGVCaRU3qI4EBWJsil?p=preview

**Comment by Digambar14** [comment]
Mistakenly closed issue...Sorry..:(

**Comment by Digambar14** [comment]
I got where is the issue. I am using this in zend. Lazyloader sending request for loading LoginController.js. But Zend is unable to find the request so its throwing an error:
**Fatal error: Uncaught exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller specified (error)' in C:\wamp\www\insite-git\insite-app\library\Zend\Controller\Plugin\Broker.php on line 336**

Do you know what may be solution for it?

**Comment by ocombe** [comment]
Hu no, that's a php issue on your server, I don't think it has anything to do with ocLazyLoad

**Comment by Digambar14** [comment]
Thanks. But if you resolve issue of "insertBefore" please let me know.

**Comment by Digambar14** [comment]
Hi,

I resolved issue with zend. Your plugin working like charm. Thanks.

Plz let me know once fix the issue of "insertBefore"

**Comment by ocombe** [comment]
Yes I'll let you know

**Comment by ocombe** [comment]
Ok it's fixed in 1.0.0-beta.1.
The final 1.0.0 should be released soon (this week).

**Comment by burakkilic** [comment]
I still have this issue. Code tries to find the anchor in <head> tags but I need to load script in <body>.

**Comment by ocombe** [comment]
Do you have an error message @burakkilic ?

**Comment by burakkilic** [comment]
I am getting following error:

    NotFoundError: Node was not found
    anchor.insertBefore(el, insertBeforeElem);

My code is:

    return $ocLazyLoad.load({
                        insertBefore: '#load_controllers_before',
                        files: [
                            'js/controllers/BillingController.js'
                        ]
                    });

And tag in the <body></body> tags is

    <div id="load_controllers_before"></div>

**Comment by ocombe** [comment]
Can you type:
```js
document.querySelector('#load_controllers_before');
```
in your console, and check if it finds the node in your webpage ?

**Comment by burakkilic** [comment]
Yes, it finds.

**Comment by ocombe** [comment]
OK found the issue, I'm searching for the node in head like you said, instead of taking the parent of the selector... :-/
Sorry for that, thanks for the report, I'll fix it :)

**Comment by burakkilic** [comment]
Thank you. Waiting for the news:)

**Comment by ocombe** [comment]
Fixed :)

**Comment by Digambar14** [comment]
Thanks dude..:)

**Comment by RSPaul** [comment]
Hi,

I am using version v1.0.9 and I am still getting the error: SyntaxError: expected expression, got '<'
http://awesomescreenshot.com/0bf5n6jsd6

**Comment by github372** [comment]
hi
this problem is because of a bug in ocLazyLoad...
this bug is:
when you write an element in your html page that want to use for "insertBefore" in ocLazyLoad, if this element is in body section of html page you get ERROR....
and if you write this element in head section of html page, every things fine and your code work..

##  **ok... you should write the element in head section of html page**

**Comment by justgeek** [comment]
if the problem presists, note that you have to define module name in lazy load returned object, i.e:

 loadMyCtrl: ['$ocLazyLoad', function ($ocLazyLoad) {
                    // you can lazy load files for an existing module
                    return $ocLazyLoad.load({
                        name:'app',//must include angular module name
                        files: ['js/controllers/BillingController.js']
                    });
                }]

**Comment by benallamar** [comment]
Hi every one,
I get the same error, insertBefore doesn't work for me even after I download the last version of the code.
Need help please 😄

**Comment by justgeek** [comment]
@benallamar can you show your code?

**Comment by benallamar** [comment]
@justgeek thank you for your answer
`.state("orders", {
      url: "/orders",
      templateUrl: "views/order/list.html",
      data: {pageTitle: 'Orders'},
      controller: "OrdersCtrl",
      resolve: {
        deps: ['$ocLazyLoad', function ($ocLazyLoad) {
          return $ocLazyLoad.load({
            name: 'MetronicApp',
            serie: true,
            insertBefore: '#ng_load_plugins_before', // load the above css files before '#ng_load_plugins_before'
            files: [
              /*
               CSS Files
               */
              'assets/global/plugins/datatables/datatables.min.css',
              'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css',
              'assets/global/css/components.min.css',
              'assets/global/css/components.min.css',
              'assets/global/css/plugins.min.css',
              /*
               JAVASCRIPT Files
               */
              'assets/global/scripts/datatable.js',
              'assets/global/plugins/datatables/datatables.min.js',
              'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js',
              'assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js',
              'assets/pages/scripts/table-datatables-buttons.min.js'
            ]
          });
        }]
      }
    })`

**Comment by justgeek** [comment]
@benallamar did you try using it without deps ? I mean put depencies elsewhere, what is serie:true ?
can you send a plunker with your code so we can debug it togther ?

**Comment by 50l3r** [comment]
I get the same error:

```
     .state('appview', {
            url: '/:AppPermalink/:ItemId',
            parent: "root",
            views: {
                'main@': {
                    template: function(stateParams) {
                        return require('../views/apps/' + stateParams.AppPermalink + '/' + stateParams.AppPermalink + '_view.html')
                    },
                    controller: 'AppController'
                }
            },
            data: {
                title: 'Dashboard',
                bodyClass: '',
                requiredLogin: true
            },
            resolve: {
                deps: ['$ocLazyLoad', '$stateParams', function($ocLazyLoad, $stateParams) {
                    var ControllerName = $stateParams.AppPermalink.charAt(0).toUpperCase() + $stateParams.AppPermalink.substr(1) + "Controller";

                    return $ocLazyLoad.load([{
                        name: 'Gestios',
                        //insertBefore: '#oclazyload',
                        files: ['/app/controllers/apps/' + ControllerName + '.js']
                    }]);
                }],
                loadMyCtrl: ['$ocLazyLoad', function($ocLazyLoad) {
                    return $ocLazyLoad.load('proyectos'); // Resolve promise and load before view
                }]
            }
        })
```

The debug log:

```
ocLazyLoad.fileLoaded /app/controllers/apps/EmpresasController.js
angular.js?58d0:14362 ocLazyLoad.fileLoaded /app/assets/css/pages/profile-2.css
angular.js?58d0:14362 ocLazyLoad.fileLoaded /app/assets/css/pages/widgets.css
angular.js?58d0:14362 ocLazyLoad.componentLoaded ["Gestios", "register", "EmpresasController"]
angular.js?58d0:14362 ocLazyLoad.moduleReloaded Gestios
```

But i dont see the console.log

**Comment by harendra21** [comment]
File is loading but shows controller is undefined

.state('login', {
            url: '/login',
            views: {
                'content': {
                    templateUrl: 'view/user/login.html',
                    controller: 'loginCtrl',
                }
            },
            resolve: {
                loginCtrl: ['$ocLazyLoad', function($ocLazyLoad) {
                    return $ocLazyLoad.load('login');
                }],
                auth: function(authService) {
                    return authService.is_auth();
                }
            }


app.config(['$ocLazyLoadProvider', 
  function($ocLazyLoadProvider) {
    //Config For ocLazyLoading
    $ocLazyLoadProvider.config({
        'debug': true, // For debugging 'true/false'
        'events': true, // For Event 'true/false'
        insertBefore: '#ng_load_plugins_before',
        'modules': [{ // Set modules initially
            name : 'login', // State1 module
            files: ['controllers/loginCtrl.js']
        },{
            name : 'state2', // State2 module
            files: ['app/components/state2/state2Module.js']
        }]
    });
  }]);



Using angular 1.4.8 & oclazyload 1.0.0 beta 1
